### ISSUE TITLE
Issue with mobile phone menu

### ISSUE THREAD

**Issue by jordanbramel** [XavierUniversity/2016-R2X-Dev#26]
When you are on mobile you cannot scroll down on the menu, the menu disappears.

**Comment by sparks12XU** [comment]
This works on Safari but is breaking in Chrome.   Something broke when other updates were done. 

The "template" is a bit bloated and a bit of a house of cards. To keep things clean/simple I would suggest starting with a basic shell and moving features/styles then add extra features.  This eliminates any potential issues when migrated into CF and less guess work and tracing out issues.

**Comment by sparks12XU** [comment]
Fixed the issue in Chrome on mobile.
